version: 3.9;

services:
  redisCampusHubTS: 
    image: redis:latest
    restart: always
    container_name: redisCampusHubTS
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - campus_network

  db: 
    image: mongo
    restart: always
    container_name: campusHubTS
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: myroot
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: campusHubTS
    volumes:
      - mongo_data:/data/db

volumes: 
  mongo_data:
  redis_data:

networks:
  campus_network:
    driver: bridge